# Numpy
1.Numpy is a general purpose array proceesing packages.


2.Numpy was created to work with multidimensional arrays.


3.It is the fundamental package for scientific computing


3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)]


In [2]:
!pip install NumPy

import numpy as np

Defaulting to user installation because normal site-packages is not writeable


In [5]:
#Array creation
a=np.array(10)
type(a)


numpy.ndarray

In [6]:
#Zero dimensional array


In [8]:
z=np.array(10)

z.ndim

0

In [9]:
#One dimensional array

In [10]:
o=np.array([10,12,14,16])
o.ndim

1

In [11]:
#Two dimensional array

In [12]:
t=np.array([[10,12,13,14]])
t.ndim

2

In [13]:
#Three dimensional array

In [15]:
th=np.array([[[10,11,15,16]]])
th.ndim

3

In [16]:
#Change the data type of the array elements

In [17]:
a=np.array([10,15,54,30])

In [18]:
a.dtype

dtype('int32')

In [20]:
a=np.array([10,14,54,30],dtype='float')
print(a.dtype)
a

float64


array([10., 14., 54., 30.])

In [23]:
a=np.arange(1,21,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [25]:
b=np.linspace(1,5,15,retstep=True)
b

(array([1.        , 1.28571429, 1.57142857, 1.85714286, 2.14285714,
        2.42857143, 2.71428571, 3.        , 3.28571429, 3.57142857,
        3.85714286, 4.14285714, 4.42857143, 4.71428571, 5.        ]),
 0.2857142857142857)

In [27]:
z=np.zeros([2,2])
z

array([[0., 0.],
       [0., 0.]])

In [28]:
o=np.ones([5,5])
o

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [29]:
r=np.random.rand(5,5)
r

array([[0.8032822 , 0.58389113, 0.79858271, 0.09186503, 0.55384981],
       [0.33582043, 0.02998858, 0.61965757, 0.65685546, 0.65981804],
       [0.62215624, 0.3048183 , 0.83319347, 0.34287842, 0.26721866],
       [0.59035216, 0.39482303, 0.29340822, 0.98870655, 0.37782675],
       [0.8257936 , 0.67318229, 0.0437512 , 0.4919358 , 0.05417524]])

In [31]:
r=np.random.randint(5,size=10)
r

array([0, 2, 4, 0, 1, 2, 2, 2, 0, 2])

# Slicing and indexing of arrays

In [32]:
a=np.array([[1,2,3],[4,5,6]])

In [33]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
a[0,0]

1

In [35]:
a[1,2]

6

In [36]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
a[0,1:]

array([2, 3])

In [38]:
a[0:,1:]

array([[2, 3],
       [5, 6]])

In [39]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
#1 and 6

In [41]:
a[[0,1],[0,2]]

array([1, 6])

In [42]:
#3 and 4

In [43]:
a[[0,1],[2,0]]

array([3, 4])

# Reshaping the array

In [44]:
a=np.random.rand(5,2)

In [45]:
a

array([[0.97019496, 0.65259919],
       [0.77515162, 0.13541421],
       [0.72075484, 0.03285351],
       [0.47087718, 0.4191421 ],
       [0.97095183, 0.55394243]])

In [46]:
a.reshape(2,5)

array([[0.97019496, 0.65259919, 0.77515162, 0.13541421, 0.72075484],
       [0.03285351, 0.47087718, 0.4191421 , 0.97095183, 0.55394243]])

In [47]:
a.reshape(10,1)

array([[0.97019496],
       [0.65259919],
       [0.77515162],
       [0.13541421],
       [0.72075484],
       [0.03285351],
       [0.47087718],
       [0.4191421 ],
       [0.97095183],
       [0.55394243]])

In [48]:
a.reshape(1,10)

array([[0.97019496, 0.65259919, 0.77515162, 0.13541421, 0.72075484,
        0.03285351, 0.47087718, 0.4191421 , 0.97095183, 0.55394243]])

In [49]:
a.reshape(5,-1)

array([[0.97019496, 0.65259919],
       [0.77515162, 0.13541421],
       [0.72075484, 0.03285351],
       [0.47087718, 0.4191421 ],
       [0.97095183, 0.55394243]])

# Aggregate functions

In [50]:
a.min()

0.03285351164296679

In [51]:
a.std()

0.3004641906864878

In [52]:
a.var()

0.0902787298848861

In [53]:
a.mean()

0.5701881876417951

# Stacking

In [54]:
a=np.array([1,2,3,4,5])
b=np.array([4,5,6,8,7])

In [55]:
np.hstack([a,b])

array([1, 2, 3, 4, 5, 4, 5, 6, 8, 7])

In [56]:
np.vstack([a,b])

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 8, 7]])